# Generated by Django 4.2.1 on 2023-06-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='audio',
            field=models.FileField(blank=True, default=1, upload_to='audios/', verbose_name='Archivo de audio'),
            preserve_default=False,
        ),
    ]
