# Generated by Django 4.2.1 on 2023-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
