# Generated by Django 4.2.1 on 2023-06-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_1', '0002_usermessage_email_usermessage_image_usermessage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Proyecto_1.customuser'),
        ),
    ]
